name: pre-release

on:
    push:
        branches:
            - main
        tags-ignore:
            - "*"

jobs:
    build:
        uses: ./.github/workflows/build-jar.yaml

    publish-pre-release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4

            - uses: marvinpinto/action-automatic-releases@v1.2.1
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: latest
                  prerelease: true
                  title: Development Build
                  files: |
                      **/*.jar
